### ISSUE TITLE
documents

### ISSUE THREAD

**Issue by lesserror** [suhridgupta/K8s-Custom-Scheduler#1]
May I ask what document you are referring to? Thank you~

**Comment by suhridgupta** [comment]
For the python script, I followed this article: https://sebgoa.medium.com/kubernetes-scheduling-in-python-3588f4928b13
For the scheduling example: I used the official Horizontal Pod Autoscaler walkthrough and overrode the default-scheduler: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

Hope that helps!
